apiVersion: apps/v1
kind: Deployment
metadata:
  name: reviews-deployment
  namespace: backend-store
  labels:
    app: reviews
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reviews
  template:
    metadata:
      labels:
        app: reviews
    spec:
      containers:
      - name: backend-reviews
        image: chaphe/backend-reviews-image:1.0
        ports:
        - containerPort: 3000
        env:
        - name: MONGODB_HOST
          valueFrom:
            configMapKeyRef:
              name: mongo-config
              key: mongo-url
---
apiVersion: v1
kind: Service
metadata:
  name: reviews-service
  namespace: backend-store
spec:
  type: NodePort
  selector:
    app: reviews
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30100